import { useState } from 'react';
import { Activity, AudioLines, FlaskConical, Play, SlidersHorizontal, Download } from 'lucide-react';
import { api } from '../api/client';
import type { Simulation, Sweep } from '../api/client';
export function SimulationPanel({onQuery,onError}:{onQuery:(id:string)=>void;onError:(s:string)=>void}) {
 const [scheme,setScheme]=useState('synapse_count'),[tau,setTau]=useState(20),[threshold,setThreshold]=useState(0);
 const [result,setResult]=useState<Simulation|null>(null),[sweep,setSweep]=useState<Sweep|null>(null),[busy,setBusy]=useState('');
 async function run(full=false){setBusy(full?'sweep':'sim');try{if(full){const r=await api<Sweep>('/circuit/courtship/sensitivity');setSweep(r);onQuery(r.query_id);}else{const r=await api<Simulation>(`/circuit/courtship/simulate?weight_scheme=${scheme}&tau_ms=${tau}&min_weight=${threshold}`);setResult(r);onQuery(r.query_id);}}catch(e){onError((e as Error).message);}finally{setBusy('');}}
 return <div className="simulation-content"><div className="case-intro"><span className="square-icon"><AudioLines size={24}/></span><div><span className="overline">FLAGSHIP CASE STUDY · ENGINEERING SANDBOX</span><h2>Courtship circuit laboratory</h2><p>Explore a spiking model. Then question every assumption.</p></div><span className="badge amber-badge">NOT VALIDATED</span></div><div className="notice"><FlaskConical size={17}/><p>The P1 → pIP10 → wing-motor circuit is the research target. This sandbox uses <strong>abstract synthetic cells</strong>, not that extracted circuit. No empirical song recording is loaded.</p></div>
 <section className="panel"><div className="panel-heading"><h3><SlidersHorizontal size={16}/> Model assumptions</h3><span className="micro">BRIAN2 / LEAKY INTEGRATE-AND-FIRE</span></div><div className="sim-controls"><label>WEIGHT PROXY<select value={scheme} onChange={e=>setScheme(e.target.value)}><option value="synapse_count">Raw count</option><option value="log">Log-scaled count</option><option value="uniform">Uniform weights</option></select></label><label>MEMBRANE TIME CONSTANT<select value={tau} onChange={e=>setTau(+e.target.value)}>{[10,20,30].map(t=><option key={t} value={t}>{t} ms</option>)}</select></label><label>COUNT THRESHOLD<select value={threshold} onChange={e=>setThreshold(+e.target.value)}><option value={0}>No threshold</option><option value={100}>100 synthetic counts</option></select></label><button className="button primary" disabled={!!busy} onClick={()=>void run()}><Play size={15}/>{busy==='sim'?'Simulating…':'Run simulation'}</button></div></section>
 <section className="panel"><div className="panel-heading"><h3><Activity size={16}/> Modeled spike activity</h3><span className="badge green-badge">500 ms window</span></div>{!result?<div className="empty-state"><Activity size={36}/><h3>A model is a hypothesis, not an answer.</h3><p>Run the LIF network to inspect its spike raster and motor output.</p><span className="mono tiny">Δt 0.2 ms · 2 ms synaptic delay · 3 ms refractory period</span></div>:<><div className="sim-metrics"><div><span>MOTOR SPIKES</span><strong>{result.spike_count}</strong></div><div><span>MODELED MEAN INTERVAL</span><strong>{result.mean_ipi_ms??'—'} <small>ms</small></strong></div><div><span>LITERATURE GUIDE ONLY</span><strong className="muted">~35 <small>ms</small></strong></div></div><svg className="raster" viewBox="0 0 800 280" role="img" aria-label="Modeled synthetic neuron spike raster"><rect x="129" y="15" width="414" height="225" fill="#eaf1e6"/>{result.labels.map((n,i)=><g key={n}><text x="45" y={30+i*16} textAnchor="end">{n}</text><line x1="60" x2="750" y1={25+i*16} y2={25+i*16} stroke="#e9ece4"/></g>)}{result.spikes.map((s,i)=><line key={i} x1={60+s.time/500*690} x2={60+s.time/500*690} y1={20+s.neuron*16} y2={29+s.neuron*16} stroke={s.neuron===12?'#ba704c':'#477760'} strokeWidth="1.7"/>)}{[0,100,200,300,400,500].map(t=><text key={t} x={60+t/500*690} y="264" textAnchor="middle">{t} ms</text>)}</svg><div className="audio-row"><AudioLines size={18}/><div><strong>Listen to modeled output</strong><p>Spike sonification, not a recording of fly song.</p></div><audio key={result.query_id} controls src={`/api/audio/${result.query_id}.wav`}/><a className="icon-button" title="Download WAV" href={`/api/audio/${result.query_id}.wav`} download><Download size={16}/></a></div><div className="model-notes">{result.assumptions.map(a=><p key={a}>· {a}</p>)}</div></>}</section>
 <section className="panel"><div className="panel-heading"><h3><FlaskConical size={16}/> Assumption observatory</h3><button className="button secondary small" disabled={!!busy} onClick={()=>void run(true)}>{busy==='sweep'?'Running 18 models…':'Run sensitivity sweep'} <SlidersHorizontal size={13}/></button></div>{sweep?<div className="sweep-body"><p><strong>{sweep.active_runs} / {sweep.total_runs} models</strong> produce motor spikes. This is model robustness, not biological validation.</p><div className="table-scroll"><table><thead><tr><th>Weight scheme</th><th>τ (ms)</th><th>Threshold</th><th>Motor spikes</th><th>Mean interval</th></tr></thead><tbody>{sweep.runs.map((r,i)=><tr key={i}><td>{r.scheme.replace('_',' ')}</td><td>{r.tau_ms}</td><td>{r.threshold}</td><td><div className="sweep-bar"><i style={{width:`${r.spike_count/Math.max(...sweep.runs.map(x=>x.spike_count),1)*100}%`}}/>{r.spike_count}</div></td><td>{r.mean_ipi_ms??'—'} ms</td></tr>)}</tbody></table></div><div className="conclusions">{sweep.conclusions.map(c=><span key={c.label} className={`badge ${c.robust?'green-badge':'amber-badge'}`}>{c.robust?'ROBUST':'NOT ROBUST'} · {c.label}</span>)}</div><p className="tiny muted">{sweep.validation}</p></div>:<div className="sweep-placeholder"><div className="mini-bars">{[30,55,40,80,48,64,37,74,52,88,61,45].map((v,i)=><i key={i} style={{height:v/2}}/>)}</div><div><h3>Does the result survive a different model?</h3><p>3 weight schemes × 3 time constants × 2 thresholds. Run all 18, and see what holds up.</p><span className="tiny muted">Illustrative graphic; no sweep results yet.</span></div></div>}</section></div>;
}
